version: '3.8'

services:
  backend:
    build: .
    restart: always
    environment:
      - DB_HOST=gateway01.eu-central-1.prod.aws.tidbcloud.com
      - DB_PORT=4000
      - DB_NAME=test
      - DB_USER=3YDpriSpMw23Zdg.root
      - DB_PASSWORD=lgjXy7L4VgGIEvF4
      - DEBUG=True
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../EduTraker_frontend
      args:
        - VITE_API_URL=http://localhost:8000/api
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
